-- 40 SQL Practice Questions – SH Schema

-- 1. From SH.CUSTOMERS, display customer ID, first name, last name, gender, and marital status for all female customers.

select cust_id, CUST_FIRST_NAME,CUST_LAST_NAME,CUST_GENDER,CUST_MARITAL_STATUS 
from sh.CUSTOMERS
where CUST_GENDER = 'F'

-- 2. From SH.CUSTOMERS, find customers whose last name starts with S and whose year of birth is greater than 1970.

select * 
from sh.CUSTOMERS
where CUST_LAST_NAME like 'S%'
and CUST_YEAR_OF_BIRTH > 1970

-- 3. From SH.PRODUCTS, display product ID, product name, category, and list price for products whose list price is between 100 and 500.

select PROD_ID,PROD_NAME,PROD_CATEGORY,PROD_LIST_PRICE
from sh.products
where PROD_LIST_PRICE between 100 and 500

-- 4. From SH.PRODUCTS, find products whose minimum price is less than 50 and whose status is available.

select *
from sh.PRODUCTS
where PROD_MIN_PRICE < 50 and 
PROD_VALID = 'A'

-- 5. From SH.SALES, display product ID, customer ID, quantity sold, and amount sold for transactions where the amount sold is greater than 1000.

select PROD_ID,CUST_ID,QUANTITY_SOLD,AMOUNT_SOLD
from sh.SALES
where AMOUNT_SOLD > 1000

-- 6. From SH.SALES, find transactions where the quantity sold is greater than 2 and the channel ID is 3.

select *
from sh.SALES
where quantity_sold > 2
and channel_id = 3

-- 7. From SH.CHANNELS, display channel ID and channel description for channels whose description contains the word Direct.

select channel_id, channel_desc
from sh.channels
where channel_desc like '%Direct%'

-- 8. From SH.PROMOTIONS, display promotion ID, promotion name, cost, and category where promotion cost is greater than 1000.

select promo_id,promo_name,
promo_cost,promo_category
from sh.PROMOTIONS
where promo_cost > 1000

-- 9. From SH.PROMOTIONS, find promotions whose end date is greater than their begin date and whose promotion cost is greater than 500.

select *
from sh.PROMOTIONS
where PROMO_END_DATE > PROMO_BEGIN_DATE
and promo_cost > 500

-- 10. From SH.COUNTRIES, display country ID, country name, and region ID for countries belonging to region ID 52790.

select country_id,country_name,country_region_id
from sh.COUNTRIES
where COUNTRY_REGION_ID = 52790

-- 11. From SH.TIMES, display time ID, day name, calendar month name, and calendar year for dates belonging to the year 2000.

select time_id,day_name,CALENDAR_MONTH_NAME,CALENDAR_YEAR
from sh.times
where CALENDAR_YEAR = 2000

-- 12. From SH.TIMES, find all dates where the calendar month name is December and the calendar year is 2001.

select *
from sh.TIMES
where CALENDAR_MONTH_NAME = 'December'
and CALENDAR_YEAR = 2001

-- 13.From SH.COSTS, display product ID, time ID, unit cost, and unit price where unit price is greater than unit cost.

select prod_id,time_id,unit_cost,unit_price
from sh.costs
where unit_price > unit_cost

-- 14.From SH.COSTS, find records where unit cost is greater than 100 and unit price is less than 1000.

select *
from sh.COSTS
where unit_cost > 100
and UNIT_PRICE < 1000

-- 15.From SH.SUPPLEMENTARY_DEMOGRAPHICS, display customer ID, education, occupation, and household size for customers whose household size is greater than 3.

select cust_id,education,
occupation,HOUSEHOLD_SIZE
from sh.SUPPLEMENTARY_DEMOGRAPHICS
where HOUSEHOLD_SIZE > '3'

-- GROUP BY – DIFFERENT BUSINESS QUESTIONS

-- 16. Using SH.CUSTOMERS, find the number of customers belonging to each marital status.

select CUST_MARITAL_STATUS,count(cust_id) as Number_of_customers
from sh.CUSTOMERS
group by CUST_MARITAL_STATUS

-- 17. Using SH.CUSTOMERS, find the average customer year of birth for each gender.

select cust_gender,ceil(avg(CUST_YEAR_OF_BIRTH)) as avg_birth_year
from sh.CUSTOMERS
group by CUST_GENDER

-- 18. Using SH.PRODUCTS, find the average list price of products in each product category.

select PROD_CATEGORY,round(avg(PROD_LIST_PRICE),2) as avg_list_price
from sh.products
group by PROD_CATEGORY

-- 19. Using SH.PRODUCTS, find the highest minimum price in each product subcategory.

SELECT PROD_SUBCATEGORY,max(PROD_MIN_PRICE)
from sh.products
group by PROD_SUBCATEGORY

-- 20.Using SH.SALES, calculate the total sales amount generated by each channel.

select channel_id,sum(amount_sold) as total_amount
from sh.SALES
GROUP by channel_id

-- 21.Using SH.SALES, find the average sales amount for each promotion.

select PROMO_ID,round(avg(amount_sold),2) as total_amount
from sh.SALES
GROUP by PROMO_ID

-- 23.Using SH.PROMOTIONS, calculate the total promotion cost for each promotion category.

select PROMO_CATEGORY,sum(PROMO_cost) as total_promo_cost
from sh.PROMOTIONS
group by PROMO_CATEGORY

-- 24.Using SH.COUNTRIES, count the number of countries belonging to each region.

select COUNTRY_REGION,count(country_id) as No_of_countries
from sh.COUNTRIES
group by COUNTRY_REGION

-- 25.Using SH.COSTS, calculate the average unit cost for each product.

select PROD_ID,round(avg(unit_cost),2) as avg_unit_cost
from sh.COSTS
group by PROD_ID

TWO-LEVEL GROUP BY

-- 26.Using SH.CUSTOMERS, count customers by gender and marital status.

select cust_gender,CUST_MARITAL_STATUS,count(cust_id)
from sh.customers
group by CUST_GENDER,CUST_MARITAL_STATUS

-- 27.Using SH.PRODUCTS, count products by product category and product subcategory.

SELECT PROD_CATEGORY,PROD_SUBCATEGORY,
count(prod_id)
from sh.PRODUCTS
group  by PROD_CATEGORY,PROD_SUBCATEGORY

-- 28.Using SH.SALES, calculate total sales amount for each product and channel combination.

select PROD_ID,CHANNEL_ID,
sum(amount_sold)
from sh.SALES
group by PROD_ID,CHANNEL_ID

-- 29.Using SH.SALES, calculate total quantity sold for each channel and promotion combination.

select CHANNEL_ID,PROMO_ID,
sum(QUANTITY_SOLD)
from sh.SALES
group by CHANNEL_ID,PROMO_ID

-- 30.Using SH.COSTS, find the average unit cost for each product and promotion combination.

select prod_id,promo_id,
round(avg(unit_cost),2)
from sh.COSTS
group by prod_id,promo_id

WHERE + GROUP BY

-- 31.From SH.SALES, consider only transactions where AMOUNT_SOLD > 500 and calculate total sales amount for each channel.

select channel_id,sum(AMOUNT_SOLD)
from sh.sales
where AMOUNT_SOLD > 500
group by CHANNEL_ID

-- 32.From SH.PRODUCTS, consider only products whose list price is greater than 100 and find the average list price for each product category.

select PROD_CATEGORY,
round(avg(prod_list_price),2) as average
from sh.PRODUCTS
where prod_list_price > 100
group by PROD_CATEGORY

-- 33.From SH.CUSTOMERS, consider only customers born after 1970 and count them by marital status.

select CUST_MARITAL_STATUS,
count(cust_id) 
from sh.CUSTOMERS
where CUST_YEAR_OF_BIRTH > 1970
group  by CUST_MARITAL_STATUS

-- 34.From SH.PROMOTIONS, consider only promotions whose cost is greater than 500 and calculate the average promotion cost for each promotion category.

select PROMO_CATEGORY,
round(avg(promo_cost),2)
from sh.PROMOTIONS
where promo_cost > 500
group by PROMO_CATEGORY

-- 35.From SH.COSTS, consider records where unit cost is greater than 50 and calculate the maximum unit price for each product.

select PROD_ID,
max(unit_price)
from sh.COSTS
where UNIT_COST > 50
GROUP by prod_id

GROUP BY + HAVING

-- 36.Using SH.CUSTOMERS, display marital statuses having more than 100 customers.

select CUST_MARITAL_STATUS, count(cust_id) as cust_count
from sh.CUSTOMERS
group by CUST_MARITAL_STATUS
having count(cust_id) > 100

-- 37.Using SH.PRODUCTS, display product categories whose average list price is greater than 500.

select PROD_CATEGORY,round(avg(prod_list_price)) as avg_list_price
from sh.products
group by PROD_CATEGORY
having round(avg(prod_list_price)) > 500

-- 38.Using SH.SALES, display channels whose total sales amount is greater than 100000.

select CHANNEL_ID, sum(amount_sold)
from sh.SALES
group by CHANNEL_ID
having sum(amount_sold) > 100000

-- 39.Using SH.PROMOTIONS, display promotion categories whose average promotion cost is greater than 1000.

select promo_category, round(avg(promo_cost),2)
from sh.PROMOTIONS
group by PROMO_CATEGORY
having round(avg(promo_cost),2) > 1000

-- 40.Using SH.COSTS, display products whose average unit price is greater than 500.

select prod_id,round(avg(unit_price),2)
from sh.costs
group by prod_id
having round(avg(unit_price),2) > 500